# Generated by Django 6.1.1 on 2026-09-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio_referencial', models.PositiveIntegerField(verbose_name='Precio Referencial')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del servicio')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('costo_total', models.PositiveIntegerField(verbose_name='Costo Total')),
                ('estado', models.CharField(choices=[('ING', 'Ingresado'), ('REP', 'En reparación'), ('ESP', 'Esperando repuesto'), ('FIN', 'Finalizado'), ('ENT', 'Entregado')], default='ING', max_length=3, verbose_name='Estado')),
                ('tipos_de_servicio', models.ManyToManyField(related_name='servicios_realizados', to='gestion.tiposervicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servicios', to='gestion.vehiculo')),
            ],
        ),
    ]
